name: Deploy GPT2Scratch

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: LLK/scratch-gui
          ref: develop
      - run: npm install
      - uses: actions/checkout@v3
        with:
          path: ./gpt32scratch
      - run: sh ./gpt32scratch/install.sh
      - run: npm run build
      - name: npm install under gpt32scratch
        run: npm install
        working-directory: ./gpt32scratch
      - name: Build gpt32scratch.mjs for xcratch
        run: npm run build
        working-directory: ./gpt32scratch
      - name: Copy gpt32scratch.mjs to build folder
        run: cp ./gpt32scratch/dist/gpt32scratch.mjs ./build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
